# Generated by Django 3.0.8 on 2020-07-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=20)),
                ('uemail', models.EmailField(max_length=254)),
                ('ucontact', models.CharField(max_length=20)),
            ],
        ),
    ]
